import fs from "fs";
import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/sloanelybutsurely/obsidian-eink-pager
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	plugins: prod
		? []
		: [
				{
					name: "copy-to-test-vault",
					setup(build) {
						build.onEnd((result) => {
							if (result.errors.length === 0) {
								fs.copyFileSync(
									"manifest.json",
									"eink-pager-test-vault/.obsidian/plugins/eink-pager/manifest.json",
								);
								fs.copyFileSync(
									"dist/main.js",
									"eink-pager-test-vault/.obsidian/plugins/eink-pager/main.js",
								);
								console.log("copied to test vault");
							}
						});
					},
				},
		  ],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
